### ISSUE TITLE
Usage with electron-builder, after build not include librsvg-2.2.dylib

### ISSUE THREAD

**Issue by misteral** [f3lang/node-rsvg-prebuilt#2]
Hi, as I see you have electron support for node-rsvg. I have issue with release my app with svg->png feature. Issue described [here](https://github.com/electron-userland/electron-builder/issues/1357). When I switch `2gis/node-rsvg` to `f3lang/node-rsvg-prebuilt` I get the same issue.  How I can implement `f3lang/node-rsvg-prebuilt` with electron and release it into dmg. Thanks.

**Comment by f3lang** [comment]
Hi, i looked on the issue and saw, that you used electron 1.6 
Right now, the project only supports up to electron 1.5 on darwin systems. I will update the prebuilt repositories to 1.6 on monday (I don't have access to a mac before). 
Maybe then i can reproduce this issue on my system and see what is going on. 
Do you have some sample code for me, where i can reproduce it? 

One idea i have right now is the librsvg native libraries. Did you install them with homebrew under the user youre using to launch your project?

**Comment by misteral** [comment]
Thank you for quick response, [here](https://github.com/misteral/electron-boilerplate) is simpe example with f3lang/node-rsvg-prebuilt. 

>One idea i have right now is the librsvg native libraries. Did you install them with homebrew under the user youre using to launch your project?

yes


I create little [sreencast](https://monosnap.com/file/jL1Flo2BBQiMzKpfFnpHVrCnlfR44o) what explain whats happend. 
Steps in screencast:
1. I run released(dmg) example project and it work fine(`Converted finish OK` on screen). 
2. I remove `librsvg` from system. 
3. Run released app again and get fault with it. (not convert file)

I right think what is electron app should work without installed system(librsv)?

**Comment by f3lang** [comment]
Ahh.. now it seems like we are one step closer. Under darwin and linux systems this project only delivers the bindings to librsvg and relies on the preinstalled binaries (see the readme). Only for windows i did include the native libraries since it is an insane task to get librsvg and gtk running under windows. I will try to include the binaries tomorrow in the prebuilt packages, so it will work without installing the native dependencies on the system.

**Comment by misteral** [comment]
@f3lang sounds good, thank you.

**Comment by misteral** [comment]
@f3lang Hi, any updates?

**Comment by misteral** [comment]
I close the issue. Workaround is add libs into extra resources. Instructions [here. ](https://dreamconception.com/tech/electron-how-to-build-package-and-package-3rd-party-binaries-with-electron-builder/)
