### ISSUE TITLE
Missing Node ABI Version 59

### ISSUE THREAD

**Issue by LinusU** [f3lang/node-rsvg-prebuilt#3]
It would be great to upload some newer binaries ❤️

**Comment by f3lang** [comment]
Thanks for the heads-up. Will update and upload the newer binaries. 
I think i need to automate this :)

**Comment by LinusU** [comment]
Awesome 👏

**Comment by f3lang** [comment]
soo... mac and linux is already updated :) windows is going to be tricky but i will keep you updated

**Comment by LinusU** [comment]
Thank you!

**Comment by shimondoodkin** [comment]
57 missing too.
thank you for building those!

**Comment by f3lang** [comment]
Good news everyone :) 
I automated the build and the deployment of the prebuilt binaries with appveyor and travis for those environments:

- osx
- linux x64
- linux x86
- windows x64
- windows x86

All new versions are built and online now.
