### ISSUE TITLE
Hoek warning

### ISSUE THREAD

**Issue by LinusU** [f3lang/node-rsvg-prebuilt#9]
Hoek has had a recent security advisor and it would be great if we could update to latest 4.x or 5.x.

I think bumping to latest node-pre-gyp should fix it...

```
rsvg-webpack-plugin@1.0.0 /Users/linus/coding/rsvg-webpack-plugin
└─┬ librsvg-prebuilt@0.7.7
  └─┬ node-pre-gyp@0.6.39
    └─┬ hawk@3.1.3
      ├─┬ boom@2.10.1
      │ └── hoek@2.16.3  deduped
      ├── hoek@2.16.3 
      └─┬ sntp@1.0.9
        └── hoek@2.16.3  deduped
```

**Comment by LinusU** [comment]
<img width="388" alt="screen shot 2018-04-28 at 13 54 21" src="https://user-images.githubusercontent.com/189580/39396285-b65e43be-4aeb-11e8-9407-164420415ca3.png">

Seems like we should probably try and bump a few dependencies 😄

**Comment by f3lang** [comment]
Thank you very much for this, I think you are absolutely right. :+1:
Right now i am reviving the old projects, merging open pull requests and as a part of this we should upgrade the dependencies.
I'm going to have a look at this.
